### ISSUE TITLE
[Bug] State Snapshots fail with EOF

### ISSUE THREAD

**Issue by lpgeiger** [OLSF/libra#361]
# Repro With Devnet Nodes

## Generate a state snapshot

Try to create a state snapshot, accessing the backup-service of a remote.

`cargo run --release -p backup-cli --bin db-backup -- one-shot backup --backup-service-address http://157.230.15.42:6186 state-snapshot --state-version 39170318 local-fs --dir ~/epoch-archive/`

Fails with error:
2021-02-15T15:09:13.011788Z [main] ERROR storage/backup/backup-cli/src/bin/db-backup.rs:125 main_impl() failed: State snapshot backup failed: request or response body error: error reading a body from connection: unexpected EOF during chunk size line

Remote configs: 

The remote machine used for backups needs a node.yaml configuration with backup-service-address accessible by the public (ip: `0.0.0.0:6186`): 
```
storage:
  address: "127.0.0.1:6666"
  backup_service_address: "0.0.0.0:6186"
  dir: db
  grpc_max_receive_len: 100000000
  prune_window: 100000
  timeout_ms: 30000
```
